export const SEARCH_INPUT = "SEARCH_INPUT";
export const READ_MORE_BTN_HANDLER = "READ_MORE_BTN_HANDLER";

export const FETCH_EMPTY_STATE = "FETCH_EMPTY_STATE";

//Fetch

export const FETCH_DATA = "FETCH_DATA";
export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
